run:
  concurrency: 4
  timeout: 10s
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration
  skip-dirs:
    - mocks
  skip-dirs-use-default: false
  skip-files:
  modules-download-mode: readonly
  allow-parallel-runners: false
  go: ""
